### ISSUE TITLE
docker compose/cli

### ISSUE THREAD

**Issue by jauzin23** [thomst08/requestrr#10]
hey, i use CasaOs on a raspberry pi and on the "Docker CLI" area i typed 
"docker run -d \
  --name requestrr \
  -p 4545:4545 \
  -v path to config:/root/config \
  --restart=unless-stopped \
  thomst08/requestrr" and i got this screen:
![image](https://github.com/thomst08/requestrr/assets/91629535/c0ab5810-7b48-4de3-8d50-76d489fcac7c)
but i cant install it anyway. i also typed docker pull thomst08/requestrr to pull the image but, for some reason it still did not show up on casaos. Is it possible to have a different CLI ??

**Comment by thomst08** [comment]
Hey @jauzin23,

The command should work, but I'll have a look and let you know what I find.

Just to double check, the volume part looks incorrect in the image, you need to change that part to suit your needs, and that might be part the problem.
```-v /config-folder-on-pi:/root/config```. 
Only change the first part, the ```DATA/AppData/config``` looks OK, but the container path should be ```/root/config```

**Comment by thomst08** [comment]
Hey @jauzin23,

I quickly setup a test version of CasaOs on one of my spare Pi's (model 3) and installed Requestrr, I believe this is simply your volume settings, here is a copy of my container.

![image](https://github.com/thomst08/requestrr/assets/34995599/5eca5514-eda9-4a62-b913-077917b2c744)

Try to match these settings with yours and see if that helps, I had to click the icon in the "Host" textbox and created a folder for Requestrr's settings to go into.

Hope that helps.

**Comment by jauzin23** [comment]
> Hey @jauzin23,
> 
> I quickly setup a test version of CasaOs on one of my spare Pi's (model 3) and installed Requestrr, I believe this is simply your volume settings, here is a copy of my container.
> 
> ![image](https://github.com/thomst08/requestrr/assets/34995599/5eca5514-eda9-4a62-b913-077917b2c744)
> 
> Try to match these settings with yours and see if that helps, I had to click the icon in the "Host" textbox and created a folder for Requestrr's settings to go into.
> 
> Hope that helps.

Thx, it worked.

**Comment by thomst08** [comment]
Excellent, I will mark this as completed :)
