### ISSUE TITLE
Issue with login page fontawsome pack forbidden

### ISSUE THREAD

**Issue by cjannusch** [thomst08/requestrr#11]
I get a "GET https://kit.fontawesome.com/811fbb4da4.js net::ERR_ABORTED 403 (Forbidden)" Error when trying to use the login page.  It appears that the icons that were used previously are no longer available at that URL.  I tried to access this url on a different network and also recieved a 403 response.

**Comment by thomst08** [comment]
Hey @cjannusch,

Good pickup, this is coming up in my console, I can correct this in a future update.
Is this stopping you form logging in?

**Comment by cjannusch** [comment]
Yes it is stopping me from logging in, was trying to change the sonarr version from 4 to 3 because that is currently broken for me.  It would be nice (maybe just for me lol) if it defaulted to version 3.

**Comment by thomst08** [comment]
I think going forward it makes more sense for version 4 to be the default (I don't know if there is a reason to do a fresh install of version 3 going forward), but I get your point.

I will correct this error and patch it when I have a chance.

**Comment by cjannusch** [comment]
Okay thank you, I built the project on my own without the script tag and am still not getting a login page, so I'm not sure, but there may be something else i am experiencing causing my issue, but I will test your update when you get a chance and let you know if that fixes it. Thanks for the quick responses!

**Comment by cjannusch** [comment]
I managed to change the sonarr version in the settings.json without any access through the webui at all.  Might be something potentially worth it to add to the common problems wiki. I am going to close this now.
