### ISSUE TITLE
Removing Radarr and Sonarr settings for replacement with Ombi

### ISSUE THREAD

**Issue by xxxtrashcion** [thomst08/requestrr#16]
Haven't found anyone asking this and I can't figure it out.

How can I remove my Radarr/Sonarr settings?

**Comment by thomst08** [comment]
Hey @xxxtrashcion,

I just want to double check what you mean, you can disable your movie or TV show client and save, but if you change it back to the previous client later it will restore your previous API, IP, etc setting.
You want to remove these from memory completely?

**Comment by xxxtrashcion** [comment]
Fixed this by deleting the settings.json cause I'm impatient. Thank you for the quick reply though.

**Comment by thomst08** [comment]
That's all good, this is what I was going to suggest after confirming.
Currently there is no way to remove the settings through the UI once entered, only changing them.

I will look at maybe updating this in the future, glad you got it solved.
