### ISSUE TITLE
Login problem  403 font

### ISSUE THREAD

**Issue by nisked** [thomst08/requestrr#21]
![image](https://github.com/thomst08/requestrr/assets/62965290/624cd38f-d5c0-41d8-84e6-a0201abe48a9)

I use the lastest version
I  can't login, how i can fix it plz ? Thx

**Comment by thomst08** [comment]
Hey @nisked, thank for raising this with me, I'm not sure why your getting that error.
I will ha e to look into it and correct the issue in an update as it seems to be contacting an outside server to generate the styling in screen.
I the mean time, is there anything that's blocking your browser from Web access just to rule that out? Like a firewall or ad blocker?

**Comment by nisked** [comment]
No i try with 3 browser and 2 internet connection :/

**Comment by thomst08** [comment]
That's ok, thank you, I'll have a look and get back to you when I have something.
How are you setup? Using docker, windows, Linux?

**Comment by thomst08** [comment]
Hey @nisked,
I have had a look over my version and I am not seeing this issue, I have double checked and cannot find this in the latest build.
This was however, an old issue from #11, I removed the link to the source you are erroring on.
Can you please double check your version of Requestrr? The version will show in the logs when starting up.

**Comment by thomst08** [comment]
Hey @nisked,
Just following this up, are you still having this issue?

**Comment by thomst08** [comment]
Hey @nisked,

I haven't heard form you regarding this issue, please reach out if you're still having issues.
This issue was corrected in [V2.1.5](https://github.com/thomst08/requestrr/releases/tag/V2.1.5) and I can't replicated it with the latest build.
I will mark this as closed if I receive no response.
