### ISSUE TITLE
Error while getting movie details from TheMovieDb

### ISSUE THREAD

**Issue by CiegeNZ** [thomst08/requestrr#22]
Been using this for of Requestrr for quite a while (since darkalfx) with no issue, been seeing this for the past week or so but been to busy to look into it

Exception: 
```
Requestrr.WebApi.RequestrrBot.DownloadClients.Radarr.RadarrClient[0]
      Error while getting movie details from TheMovieDb: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

at Requestrr.WebApi.RequestrrBot.DownloadClients.TheMovieDb.HttpGetAsync(HttpClient client, String url) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\TheMovieDb.cs:line 63
         at Requestrr.WebApi.RequestrrBot.DownloadClients.TheMovieDb.GetMovieDetailsAsync(HttpClient client, String theMovieDbId, ILogger logger) in D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\TheMovieDb.cs:line 25
```
Able to send a command from Discord, and get a list of movies, but when selecting a title, the movie does not return for 100 seconds. After that it loads fine. API key seems to be fine.
 
Set logging to informational and copy out the TMDB API requests and they are all loading immediately in the browser. 
    
I have checked the code and confirmed that the line 25 API call is the Movie Release Dates, which is the API endpoint from the logs. I see there is an error handler that looks like it is not being hit as there is no message just an exception. 
    

Currently setting up all the dev tools on my personal laptop to check it out cos everything is on the work one.

**Comment by thomst08** [comment]
Hey @CiegeNZ,
Thanks for reaching out, I have had a quick look over the issue, but I haven't got a solution yet.
This hasn't been touched from darkalfx's build, it leads me to think ether there has been too many requests made from this API key at that point in time (but it should return another error) or TMDB's API didn't get the request or is slow to respond.

I will do some testing and see if I can work out a solution here, the wait time might need to be lowered and a second attempt might need to be made, but I will see how the tests go first.

**Comment by thomst08** [comment]
Hey @CiegeNZ,
I haven't seen this error since you opened this issue, are you still having this error?
If I don't hear anything, I will mark this issue as closed.

**Comment by CiegeNZ** [comment]
Strangely started working fine. Haven't noticed an issue for a bit so will close this issue.
