### ISSUE TITLE
"An unexpected error occurred while trying to process your request" - on tv requesting via sonarr

### ISSUE THREAD

**Issue by szanka** [thomst08/requestrr#23]
I got this error after searching choosing and requesting tv show:
"An unexpected error occurred while trying to process your request"

I search the tv show eith no problem, i choose it and when i hit request it sends an error.

I've checked sonarr setings. The connection test passes, the base url is empty on both sides, thera are no roles in the bot settings.

Movie requesting works  fine via radarr

**Comment by thomst08** [comment]
Hey @szanka,

Thanks for letting me know, just need some context, is this happening for all shows or just one?
Can you please post a copy of your logs after this error has happened?

**Comment by szanka** [comment]
I've tried couple of shows and get error on every one of them


https://github.com/thomst08/requestrr/assets/26609719/06bfe8d1-353e-4d85-bd45-5947438aa269


settings:
![requester](https://github.com/thomst08/requestrr/assets/26609719/856ea792-a284-4786-a97f-8bab53c91b77)

**Comment by thomst08** [comment]
The first thing I would like you to double check is your sonarr version, if your running sonarr 3 or less, change the version in requestrr.

If it's on the correct version, then I need you to post requestrrs log

**Comment by thomst08** [comment]
Hey @szanka,

I haven't heard from you regarding this issue, are you still having issues?

**Comment by szanka** [comment]
Hello, sorry for the delay,
It does work now, the console log has shown some error with language. What
I did is I went to settings of the category and clicked everything to
"Load" settings from sonarr. The setting were the same, nothing has
changed, but when I saved settings it started working.
This is a full log from today :

fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClient[0]
>       An error while requesting tv show "Stargate Origins" from Sonarr:
> SonarrSeriesCreation failed: Bad Request - [
>         {
>           "propertyName": "LanguageProfileId",
>           "errorMessage": "Language profile does not exist",
>           "attemptedValue": -1,
>           "severity": "error",
>           "errorCode": "LanguageProfileExistsValidator",
>           "formattedMessageArguments": [],
>           "formattedMessagePlaceholderValues": {
>             "propertyName": "Language Profile Id",
>             "propertyValue": -1
>           }
>         }
>       ]
>       System.Exception: SonarrSeriesCreation failed: Bad Request - [
>         {
>           "propertyName": "LanguageProfileId",
>           "errorMessage": "Language profile does not exist",
>           "attemptedValue": -1,
>           "severity": "error",
>           "errorCode": "LanguageProfileExistsValidator",
>           "formattedMessageArguments": [],
>           "formattedMessagePlaceholderValues": {
>             "propertyName": "Language Profile Id",
>             "propertyValue": -1
>           }
>         }
>       ]
>          at
> Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage
> responseMessage, String message, Func`2 getErrorFunc) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line
> 31
>          at
> Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV3.CreateSonarrTvSeriesAsync(TvShowRequest
> request, TvShow tvShow, IReadOnlyList`1 seasons) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV3.cs:line
> 349
>          at
> Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV3.RequestTvShowAsync(TvShowRequest
> request, TvShow tvShow, TvSeason season) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV3.cs:line
> 277
> fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
>       Error while handling interaction: An error occurred while requesting
> a tv show from Sonarr
>       System.Exception: An error occurred while requesting a tv show from
> Sonarr
>          at
> Requestrr.WebApi.RequestrrBot.DownloadClients.Sonarr.SonarrClientV3.RequestTvShowAsync(TvShowRequest
> request, TvShow tvShow, TvSeason season) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Sonarr\SonarrClientV3.cs:line
> 291
>          at
> Requestrr.WebApi.RequestrrBot.TvShows.SeasonsRequestWorkflows.NormalTvSeasonRequestingWorkflow.RequestAsync(TvShowRequest
> request, TvShow tvShow, NormalTvSeason selectedSeason) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\TvShows\SeasonsRequestWorkflows\NormalTvSeasonRequestingWorkflow.cs:line
> 38
>          at
> Requestrr.WebApi.RequestrrBot.TvShows.TvShowRequestingWorkflow.RequestSeasonSelectionAsync(Int32
> tvDbId, Int32 seasonNumber) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\TvShows\TvShowRequestingWorkflow.cs:line
> 193
>          at
> Requestrr.WebApi.RequestrrBot.ChatBot.HandleTvRequestAsync(ComponentInteractionCreateEventArgs
> e) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line
> 485
>          at
> Requestrr.WebApi.RequestrrBot.ChatBot.DiscordComponentInteractionCreatedHandler(DiscordClient
> client, ComponentInteractionCreateEventArgs e) in
> D:\Users\thoms\Documents\GitHub\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line
> 334
> warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
>       Failed to determine the https port for redirect.
>


Pozdrawiam




wt., 26 mar 2024 o 23:49 thomst08 ***@***.***> napisał(a):

**Comment by edrock200** [comment]
I've run into this before, not sure if you scenario is the same, but was a rather specific use case @szanka 

If I had requestrr setup with multiple request profiles, e.g. a sonarr request profile to go into /mnt/media/a and another profile to go into /mnt/media/b for example. Lets say Show A was already in /mnt/media/a, but I went to request it in /mnt/media/b with requestrr, it would throw this error.

The other scenario was an issue with sonarr itself with regards to the Title Slug bug. If two TV shows exist with the same name, and neither has the year appended to the title in TVDB, you can't add both shows to sonarr. It will throw a title slug error. If you try to add the second show via requestrr, it would throw the the same error you noted above.

**Comment by edrock200** [comment]
I've run into this before, not sure if you scenario is the same, but was a rather specific use case @szanka 

If I had requestrr setup with multiple request profiles, e.g. a sonarr request profile to go into /mnt/media/a and another profile to go into /mnt/media/b for example. Lets say Show A was already in /mnt/media/a, but I went to request it in /mnt/media/b with requestrr, it would throw this error.

The other scenario was an issue with sonarr itself with regards to the Title Slug bug. If two TV shows exist with the same name, and neither has the year appended to the title in TVDB, you can't add both shows to sonarr. It will throw a title slug error. If you try to add the second show via requestrr, it would throw the the same error you noted above.

**Comment by thomst08** [comment]
Hey @szanka,
Just reaching out to see if this error is still occurring?
If I hear no response, I will mark this issue as closed.

**Comment by szanka** [comment]
@thomst08 youbcan close the thread. Everything is working now
