### ISSUE TITLE
[FR] - if requested item is already on the server, let requester know

### ISSUE THREAD

**Issue by bullmoose20** [thomst08/requestrr#29]
Rather than having multiple people requesting the same thing multiple times, let people know if it has been requested already or that it already exists on the media server.

**Comment by thomst08** [comment]
Hey,

This already happens, if I request something then you request the same thing before it is added to the server, your request button turns into a notify button, and you will get notified when it is available.
If it is already on the server, your request button changes to "Available" and is disabled.

**Comment by bullmoose20** [comment]
I did not know this. Great to know!
________________________________
