### ISSUE TITLE
[FR] Lidarr integration

### ISSUE THREAD

**Issue by bullmoose20** [thomst08/requestrr#30]
As subject suggests, extend the request for music/albums/artists.

**Comment by thomst08** [comment]
This is already being worked on, however, it is taking me some time as I don't always have a lot of time spare, you can find it in the [lidarr-intergration](https://github.com/thomst08/requestrr/tree/lidarr-intergration) branch.

**Comment by bullmoose20** [comment]
Fantastic and thanks for all your hard work!
________________________________

**Comment by zluckytraveler** [comment]
@thomst08 
> you can find it in the [lidarr-intergration ](https://github.com/thomst08/requestrr/tree/lidarr-intergration?rgh-link-date=2024-04-15T04%3A20%3A42Z)branch.

That brand is no longer accessible, it comes up with a 404 Error.

**Comment by thomst08** [comment]
This was has now been released in version 2.1.7.
I will mark this as closed.
