### ISSUE TITLE
Unable to connect from https

### ISSUE THREAD

**Issue by HeisenbergK** [thomst08/requestrr#34]
Hey, 

I have a box set up. I can only access it through https, which I have set up on a nginx server, that just forwards traffic.
It does so normally to all my services except requestrr. It displays a blank page and this message in the docker logs:
`Failed to determine the https port for redirect.`

Any ideas?

**Comment by thomst08** [comment]
Hey @HeisenbergK,

Thanks for reaching out.
Hmmmm, I am not sure as I have not tried to setup Requestrr like this, I might have to setup a VM and test it...
In theory, as long as you have setup Nginx to proxy the traffic correctly to Requestrr's website (which is http on port 4545) and have the correct SSL certificates...it should work fine but I do not know.

I might test this and see if I can find any issues.  But, might be a little while until I have some spare time.

**Comment by HeisenbergK** [comment]
Found a solution. First set `network_mode: host` in docker to be able to see Radarr/Sonarr.
Then in nginx, you need to set a new server in sites-enabled, listening to the subdomain set for requestrr in the DNS routing. Example:
```
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name requestrr.example.com;

  ssl_certificate /etc/nginx/ssl/example.com/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/example.com/key.pem;
  include snippets/ssl-params.conf;
  client_max_body_size 40M; # If uploading large files to application set this to 0 and remove the M
  server_tokens off; # Security

  location / {
    proxy_pass http://127.0.0.1:4545/; # Docker Container port
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location ~ /\.ht {
    deny all;
  }
}
```

Hope it helps people set up awesome servers!!

**Comment by thomst08** [comment]
Hey HeisenbergK,

Sorry, I never got a chance to look at this.  What you have found is perfect, I'm glad you found a solution.
Thank you for sharing :)
