### ISSUE TITLE
Extracting files is mangled

### ISSUE THREAD

**Issue by nostrus-dominion** [thomst08/requestrr#4]
Hello-

I know that this is an easy fix for a decently experienced end user but I was slightly annoyed when I extracted the files for this new fork and the hacks are meant to be slashes.

 
![Screenshot_20240121_091406](https://github.com/thomst08/requestrr/assets/40570775/6e11476e-f9fe-463e-add0-b42e9714eee4)

Thanks.

**Comment by nostrus-dominion** [comment]
Oh running the bot on a Debian 12 headless with kernel 6.1.0-13

**Comment by thomst08** [comment]
Hey @nostrus-dominion,
Just want to double check what you mean.
Are you talking about how the file paths are using '\' instead of the slash '/'.

**Comment by thomst08** [comment]
I have looked into this, and you are right, I have gone ahead and created new zip files for all Unix bases OSs, please have a look at the releases and double check everything is correct.
Once you confirm this is correct, I will close the issue.
Sorry, I created these on my Windows system and did not realize it would created an issue as testing on my side worked fine, but I want to make sure this step is easy for everyone.

Note: I have also created tar.gz files, going forward I will make sure to create these and zip files the correct way.

**Comment by nostrus-dominion** [comment]
Works great! Done and done.
