### ISSUE TITLE
Radarr

### ISSUE THREAD

**Issue by Nautilus34** [thomst08/requestrr#44]
Hello, 

Thank you for you work.

I have a question about how the chatbot on Discord works.

I use Requestrr and Radarr, which are not accessible from the WAN, I connect to it via VPN.

The chatbot works very well, I can add movie to Radarr.

I would like to understand technically how the request from discord can reach my server with Requestrr and Radarr.

Thank you

**Comment by thomst08** [comment]
Hey @Nautilus34,

Fair enough, the bot connects to Discords API's using a library called [DSharpPlus](https://dsharpplus.github.io/DSharpPlus/), this library allows the bot to receive messages and server updates.  I cannot explain how this works in detail as there a lot to go into depending on the depth, but all you really need to know is the bot will talk to Discords APIs and stay connected while the program is running, when it needs to send a notification it will send the message to Discord and who it is too.

When a message or command is sent to the bot, Discord will alert the program, causing it to respond to the command.  Each part of the command is checked and depends on what that command is, it will act accordingly, e.g., request or issue to report? A movie or a TV show?  What is the name of the media.
Requests asking for a movie are sent to the client setup with the bot, in your case, Radarr's API, Radarr will respond with movies found by the name given, the bot then turns those movies into a message for you to select, upon choosing a movie and requesting it, the bot will send the requested movie ID to the client application.

I hope that gives a rough outline of what is happening and answers your question, there is a lot of technical things going on here so it your question is quite broad.

**Comment by Nautilus34** [comment]
Hello @thomst08 

Thank you for your time and for the explanations. I understand how it works now, and I’ll continue to research further.
