### ISSUE TITLE
Multiple Radarr/Sonarr Instances

### ISSUE THREAD

**Issue by xmaxcooking** [thomst08/requestrr#45]
It's now recommended to run two Radarr/Sonarr instances. One for Anime Movies/Shows and one for Normal Movies/Shows, or you can make use of Quality Profiles and score different Custom Formats (CFs) as required.

https://trash-guides.info/Radarr/radarr-setup-quality-profiles-anime/
https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles-anime/

Requestrr currently only supports one default server (and therefore one quality profile) each.

It would be very helpful if it supported 

- Movies
- Animes
- TV Shows
- Anime Shows

and 

- /request tv-show
- /request anime-show
- /request movie
- /request anime-movie

**Comment by thomst08** [comment]
Hey @xmaxcooking,

Requestrr does support profiles, you can multiple request types, so movies can be one and anime-movie can be another each pointing to different profiles.  You can create as many of these aa you like for movies or tv shows. 

But you have a point with the other things, I would like to support multiple servers, but this will be a little while before I can being work.

Will look into this and see if I can improve this area in the future.

**Comment by xmaxcooking** [comment]
Oh, I'm very sorry. 

Overseerr Category Settings didn't ring any bells for me. I expected that to be for tags only. 

It's actually called "Destinations" in overseerr.

**Comment by xmaxcooking** [comment]
Can confirm that this works as needed.
