### ISSUE TITLE
Providing musl builds

### ISSUE THREAD

**Issue by engels74** [thomst08/requestrr#5]
Hello mate :). Thanks for taking the time to revive requestrr.

I've had a very short chat with [hotio](https://github.com/hotio), who previously had requestrr in his "fleet" of containers. It was since deprecated, since the old version of requestrr was archived.

But he (we) needs musl builds. Can you provide those? I'm guessing they're needed for working nicely with Alpine Linux, that hotio uses for his base image for all his containers.

Kind regards,
Engels

**Comment by thomst08** [comment]
Hey @engels74,

Thanks for reaching out, I can look into that for future releases, especially if it helps others :)

**Comment by thomst08** [comment]
Hey @engels74,

I have had a look and created some musl builds (both x64 and arm64), these have been uploaded to the latest release.
I setup a VM of Alpine Linux and tested the build, x64 build is working just fine for me so we should be good to go :)

Going forward, I will release new musl builds in tar files only (want to phase out the zip files for Unix OSs)
