### ISSUE TITLE
Executing Requestrr.Webapi results in chmod +x ./dotnet-install.sh on Debian 12

### ISSUE THREAD

**Issue by danaimone** [thomst08/requestrr#7]
Hi,

Followed setup instructions as per the wiki, extracting tarball, installed .NET Runtime 8.0.1, but when I try to execute the Requestrr.WebAPI, I get
`-bash: ./Requestrr.WebApi: cannot execute binary file: Exec format error`

I tried `chmod u+x Requestrr.WebApi` but to no avail. I used the tar ball so I'd expect folder and file permissions to be fine, and I tried installing .NET SDK and the runtime stand alone, both using Microsoft's dotnet install script as well as apt packages.

Not sure if I am missing something from the installation or this is an issue in Debian 12. 

OS Info:
`PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`
This is being virtualized through a LXC container on Proxmox, but don't believe that should be of any significance.

**Comment by danaimone** [comment]
Ignore me. I downloaded the arm tarball..

**Comment by thomst08** [comment]
All good, glad it's working. :)

**Comment by danaimone** [comment]
Thanks for making this. Really easy to get the bot up and running, took all of 10 minutes!
