### ISSUE TITLE
stuck at Sending...

### ISSUE THREAD

**Issue by jauzin23** [thomst08/requestrr#8]
hey, im not being able to request any movie or tv show because the bot just gets stuck at "Sending.....".
![image](https://github.com/thomst08/requestrr/assets/91629535/4bd2fc63-44e9-4afa-91ca-57894e4f1770)
is it possible that the problem is that i downloaded it from a casaOS AppStore??

**Comment by thomst08** [comment]
Hey @jauzin23,

That's no problem, can you please post your log?
If your unsure where to find it, this guide should help: https://github.com/thomst08/requestrr/wiki/Where-are-the-logs%3F

As for putting this on the app store, I think I would need to have an apple device and pay for a dev licence, I don't have ether but I can look into it. I'm afraid that might be something I can't do.

**Comment by jauzin23** [comment]
Hey, seems like the version I downloaded was a old one. Downloaded the one on this github and it worked. Thanks anyway

**Comment by thomst08** [comment]
Excellent, that is one of the common issues for this, glad you got it sorted, I will mark this as resolved :)
